# basic options
title: pymd
author: pythonXadds
email: adamhughes131117@gmail.com
description: A wonderful site
#twitter_username: jekyllrb
github_username:  pythonxadds

# Build settings
markdown: kramdown
theme: minima
