# basic options
title: PYMD'S BLOG
author: pythonXadds
email: adamhughes131117@gmail.com
description: a few of my jottings
#twitter_username: jekyllrb
github_username:  pythonxadds



# Build settings

theme: minima 

skin: dark



